#
# This file began as an auto-generated MPLAB script in the Harmony3 repository
# of example applications. It is part of a complex maze of makefiles and control
# variables in which the final makefile contains hundreds of literal insertions
# of directory paths, so that no change of control variable can re-configure the
# make for another platform. This maze is auto-generated by MPLAB, but we will
# not be using MPLAB, so our ultimate plan is to combine all the makefiles into
# one and to permit the makefile to be re-configured by single control variable
# changes.
#
# Kevan Hashemi, Open Source Instruments Inc., 2025.
#

include Makefile

MKDIR=mkdir -p
RM=rm -f 
MV=mv 
CP=cp 
CND_CONF=pic32mz_ef_sk

ifeq ($(TYPE_IMAGE), DEBUG_RUN)
IMAGE_TYPE=debug
OUTPUT_SUFFIX=elf
DEBUGGABLE_SUFFIX=elf
FINAL_IMAGE=${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX}
else
IMAGE_TYPE=production
OUTPUT_SUFFIX=hex
DEBUGGABLE_SUFFIX=elf
FINAL_IMAGE=${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX}
endif

ifeq ($(COMPARE_BUILD), true)
COMPARISON_BUILD=-mafrlcsj
else
COMPARISON_BUILD=
endif

OBJECTDIR=build/${CND_CONF}/${IMAGE_TYPE}
DISTDIR=dist/${CND_CONF}/${IMAGE_TYPE}
SRC_DIRS := src
SOURCEFILES := $(shell find $(SRC_DIRS) -type f \( -name '*.c' -o -name '*.S' \))
OBJECTFILES := $(patsubst src/%, $(OBJECTDIR)/src/%, $(SOURCEFILES:.c=.o))
OBJECTFILES := $(OBJECTFILES:.S=.o)
POSSIBLE_DEPFILES := $(OBJECTFILES:.o=.o.d)

CFLAGS=
ASFLAGS=
LDLIBSOPTIONS=

# fixDeps replaces a bunch of sed/cat/printf statements that slow down the build
FIXDEPS=fixDeps

.build-conf:
ifneq ($(INFORMATION_MESSAGE), )
	@echo $(INFORMATION_MESSAGE)
endif
	${MAKE} -f Makefile-pic32mz_ef_sk.mk ${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX}

MP_PROCESSOR_OPTION=32MZ2048EFH100
MP_LINKER_FILE_OPTION=,--script="src/config/pic32mz_ef_sk/p32MZ2048EFH100.ld"

# ------------------------------------------------------------------------------------
# Rules for buildStep: assemble
ifeq ($(TYPE_IMAGE), DEBUG_RUN)
else
endif

# ------------------------------------------------------------------------------------
# Rules for buildStep: assembleWithPreprocess
ifeq ($(TYPE_IMAGE), DEBUG_RUN)
${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o: src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.S
	@${MKDIR} "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src" 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.ok ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.err 
	${MP_CC} $(MP_EXTRA_AS_PRE) -D__DEBUG -D__MPLAB_DEBUGGER_ICD4=1 -c -mprocessor=$(MP_PROCESSOR_OPTION) -MMD -MF "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d" -o ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.S -DXPRJ_pic32mz_ef_sk=$(CND_CONF) -Wa,--defsym=__MPLAB_BUILD=1$(MP_EXTRA_AS_POST),-MD="${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.asm.d",--defsym=__ICD2RAM=1,--defsym=__MPLAB_DEBUG=1,--gdwarf-2,--defsym=__DEBUG=1,--defsym=__MPLAB_DEBUGGER_ICD4=1 -mdfp="${DFP_DIR}"
	@${FIXDEPS} "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d" "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.asm.d" -t $(SILENT) -rsi ${MP_CC_DIR}../ 
	
else
${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o: src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.S
	@${MKDIR} "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src" 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o 
	@${RM} ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.ok ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.err 
	${MP_CC} $(MP_EXTRA_AS_PRE) -c -mprocessor=$(MP_PROCESSOR_OPTION) -MMD -MF "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d" -o ${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.S -DXPRJ_pic32mz_ef_sk=$(CND_CONF) -Wa,--defsym=__MPLAB_BUILD=1$(MP_EXTRA_AS_POST),-MD="${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.asm.d",--gdwarf-2 -mdfp="${DFP_DIR}"
	@${FIXDEPS} "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.d" "${OBJECTDIR}/src/config/pic32mz_ef_sk/library/tcpip/src/tcpip_helper_c32.o.asm.d" -t $(SILENT) -rsi ${MP_CC_DIR}../ 
	
endif

# ------------------------------------------------------------------------------------
# Rules for buildStep: compile
ifeq ($(TYPE_IMAGE), DEBUG_RUN)
$(OBJECTDIR)/%.o : %.c
	@mkdir -p $(dir $@)
	@echo Compiling $<
	$(MP_CC) $(MP_EXTRA_CC_PRE) \
		-g -D__DEBUG -D__MPLAB_DEBUGGER_ICD4=1 -fframe-base-loclist \
		-x c -c -mprocessor=$(MP_PROCESSOR_OPTION) \
		-ffunction-sections -fdata-sections -O1 -fno-common \
		-DHAVE_CONFIG_H -DWOLFSSL_IGNORE_FILE_WARN \
		-I"src" -I"src/config/pic32mz_ef_sk" -I"src/config/pic32mz_ef_sk/library" \
		-I"src/config/pic32mz_ef_sk/library/tcpip/src" \
		-I"src/config/pic32mz_ef_sk/library/tcpip/src/common" \
		-I"src/third_party/wolfssl" -I"src/third_party/wolfssl/wolfssl" \
		-Werror -Wall -MP -MMD -MF "$@.d" \
		-o $@ \
		$< \
		-DXPRJ_pic32mz_ef_sk=$(CND_CONF) $(COMPARISON_BUILD) -mdfp="$(DFP_DIR)"
else
$(OBJECTDIR)/%.o : %.c
	@mkdir -p $(dir $@)
	@echo Compiling $<
	$(MP_CC) $(MP_EXTRA_CC_PRE) \
		-g -x c -c -mprocessor=$(MP_PROCESSOR_OPTION) \
		-ffunction-sections -fdata-sections -O1 -fno-common \
		-DHAVE_CONFIG_H -DWOLFSSL_IGNORE_FILE_WARN \
		-I"src" -I"src/config/pic32mz_ef_sk" -I"src/config/pic32mz_ef_sk/library" \
		-I"src/config/pic32mz_ef_sk/library/tcpip/src" \
		-I"src/config/pic32mz_ef_sk/library/tcpip/src/common" \
		-I"src/third_party/wolfssl" -I"src/third_party/wolfssl/wolfssl" \
		-Werror -Wall -MP -MMD -MF "$@.d" \
		-o $@ \
		$< \
		-DXPRJ_pic32mz_ef_sk=$(CND_CONF) $(COMPARISON_BUILD) -mdfp="$(DFP_DIR)"
endif

# ------------------------------------------------------------------------------------
# Rules for buildStep: compileCPP
ifeq ($(TYPE_IMAGE), DEBUG_RUN)
else
endif

# ------------------------------------------------------------------------------------
# Rules for buildStep: link
ifeq ($(TYPE_IMAGE), DEBUG_RUN)
${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX}: ${OBJECTFILES} Makefile-${CND_CONF}.mk src/config/pic32mz_ef_sk/p32MZ2048EFH100.ld
	@${MKDIR} ${DISTDIR} 
	${MP_CC} $(MP_EXTRA_LD_PRE) -g -mdebugger -D__MPLAB_DEBUGGER_ICD4=1 -mprocessor=$(MP_PROCESSOR_OPTION) -o ${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX} ${OBJECTFILES} -DXPRJ_pic32mz_ef_sk=$(CND_CONF) $(COMPARISON_BUILD) -mreserve=data@0x0:0x37F -Wl,--defsym=__MPLAB_BUILD=1$(MP_EXTRA_LD_POST)$(MP_LINKER_FILE_OPTION),--defsym=__MPLAB_DEBUG=1,--defsym=__DEBUG=1,-D=__DEBUG_D,--defsym=__MPLAB_DEBUGGER_ICD4=1,--defsym=_min_heap_size=64960,--gc-sections,--no-code-in-dinit,--no-dinit-in-serial-mem,-Map="${DISTDIR}/${PROJECTNAME}.${IMAGE_TYPE}.map",--memorysummary,${DISTDIR}/memoryfile.xml -mdfp="${DFP_DIR}"
	
else
${DISTDIR}/P3053.${IMAGE_TYPE}.${OUTPUT_SUFFIX}: ${OBJECTFILES} Makefile-${CND_CONF}.mk src/config/pic32mz_ef_sk/p32MZ2048EFH100.ld
	@${MKDIR} ${DISTDIR} 
	${MP_CC} $(MP_EXTRA_LD_PRE) -mprocessor=$(MP_PROCESSOR_OPTION) -o ${DISTDIR}/P3053.${IMAGE_TYPE}.${DEBUGGABLE_SUFFIX} ${OBJECTFILES} -DXPRJ_pic32mz_ef_sk=$(CND_CONF) $(COMPARISON_BUILD) -Wl,--defsym=__MPLAB_BUILD=1$(MP_EXTRA_LD_POST)$(MP_LINKER_FILE_OPTION),--defsym=_min_heap_size=64960,--gc-sections,--no-code-in-dinit,--no-dinit-in-serial-mem,-Map="${DISTDIR}/${PROJECTNAME}.${IMAGE_TYPE}.map",--memorysummary,${DISTDIR}/memoryfile.xml -mdfp="${DFP_DIR}"
	${MP_CC_DIR}/xc32-bin2hex ${DISTDIR}/P3053.${IMAGE_TYPE}.${DEBUGGABLE_SUFFIX} 
endif

.clean-conf:
	${RM} -r ${OBJECTDIR}
	${RM} -r ${DISTDIR}

DEPFILES=$(wildcard ${POSSIBLE_DEPFILES})
ifneq (${DEPFILES},)
include ${DEPFILES}
endif
