#
# This file began as an auto-generated MPLAB script in the Harmony3 repository
# of example applications. It is part of a complex maze of makefiles and control
# variables in which the final makefile contains hundreds of literal insertions
# of directory paths, so that no change of control variable can re-configure the
# make for another platform. This maze is auto-generated by MPLAB, but we will
# not be using MPLAB, so our ultimate plan is to combine all the makefiles into
# one and to permit the makefile to be re-configured by single control variable
# changes.
#
# Kevan Hashemi, Open Source Instruments Inc., 2025.
#

#
# Location of the processor device pack. We are using the one in the Harmony3
# repository. We don't copy the device pack into our project because it is 
# about half a Gigabyte.
#
DFP_DIR=/Users/kevan/Code/Harmony3/dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.58

#
# The build product locations. The ultimate programming output is a hex file. We
# have production, distribution and debug output directories, as set up by the
# original makefiles generated by MPLAB.
#
CND_BASEDIR=`pwd`
CND_ARTIFACT_DIR_pic32mz_ef_sk=dist/pic32mz_ef_sk/production
CND_ARTIFACT_NAME_pic32mz_ef_sk=P3053.production.hex
CND_ARTIFACT_PATH_pic32mz_ef_sk=dist/pic32mz_ef_sk/production/P3053.production.hex

#
# Lower case to upper case added layer of complexity, I guess.
#
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin
RANLIB=ranlib

#
# Stuff that manages sub-projects, but have no idea what a sub-project is, want
# to get rid of this eventually.
#
SUB_no=NO
SUBPROJECTS=${SUB_${SUB}}
BUILD_SUBPROJECTS_=.build-subprojects
BUILD_SUBPROJECTS_NO=
BUILD_SUBPROJECTS=${BUILD_SUBPROJECTS_${SUBPROJECTS}}
CLEAN_SUBPROJECTS_=.clean-subprojects
CLEAN_SUBPROJECTS_NO=
CLEAN_SUBPROJECTS=${CLEAN_SUBPROJECTS_${SUBPROJECTS}}
PROJECTNAME=P3053
DEFAULTCONF=pic32mz_ef_sk
CONF=${DEFAULTCONF}
ALLCONFS=pic32mz_ef_sk 

#
# We want to get rid of any reference or use of the MPLAB files, but have so far
# failed to figure out how to eliminate use of the MPLAB dependency fixing
# script.
#
PATH_TO_IDE_BIN=/Applications/microchip/mplabx/v6.25/mplab_platform/bin/
PATH:=$(PATH_TO_IDE_BIN):$(PATH)
MP_JAVA_PATH="/Applications/microchip/mplabx/v6.25/sys/java/zulu8.80.0.17-ca-fx-jre8.0.422-macosx_x64/zulu-8.jre/Contents/Home/bin/"
DEP_GEN=${MP_JAVA_PATH}java -jar "/Applications/microchip/mplabx/v6.25/mplab_platform/bin/extractobjectdependencies.jar"

#
# Not sure if this is ever used.
#
OS_CURRENT="$(shell uname -s)"

#
# All the x32 build tools: compilers, linkers, archivers, and assemblers.
#
MP_CC="/Applications/microchip/xc32/v4.60/bin/xc32-gcc"
MP_CPPC="/Applications/microchip/xc32/v4.60/bin/xc32-g++"
MP_AS="/Applications/microchip/xc32/v4.60/bin/xc32-as"
MP_LD="/Applications/microchip/xc32/v4.60/bin/xc32-ld"
MP_AR="/Applications/microchip/xc32/v4.60/bin/xc32-ar"
MP_CC_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_CPPC_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_AS_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_LD_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_AR_DIR="/Applications/microchip/xc32/v4.60/bin"

#
# The phony target makes sure that the subsequent build target is not satisfied
# by the mere existence of the build directory, but instead executes its recipe
# regardless of the state of the build.
#
.PHONY: build

build: 
	${MAKE} -f Makefile-${CONF}.mk SUBPROJECTS=${SUBPROJECTS} .build-conf

clean:
	${MAKE} -f Makefile-${CONF}.mk SUBPROJECTS=${SUBPROJECTS} .clean-conf


