#
# The P3053A Makefile.
#
# Kevan Hashemi, Open Source Instruments Inc., 2025.
#

#
# Location of the processor device pack. We are using the one in the Harmony3
# repository. We don't copy the device pack into our project because it is 
# about half a Gigabyte.
#
DFP_DIR=/Users/kevan/Code/Harmony3/dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.58

#
# The location of the project files and the project name.
#
PROJECT=P3053
CONF=pic32mz_ef_sk
CPU=32MZ2048EFH100
CPULD="src/config/pic32mz_ef_sk/p32MZ2048EFH100.ld"

#
# The build product locations. The ultimate programming output is a hex file. We
# have production, distribution and debug output directories, as set up by the
# original makefiles generated by MPLAB.
#
CND_BASEDIR=`pwd`
CND_ARTIFACT_DIR_pic32mz_ef_sk=dist/pic32mz_ef_sk/production
CND_ARTIFACT_NAME_pic32mz_ef_sk=$(PROJECT).production.hex
CND_ARTIFACT_PATH_pic32mz_ef_sk=dist/pic32mz_ef_sk/production/$(PROJECT).production.hex

#
# All the x32 build tools: compilers, linkers, archivers, and assemblers.
#
MP_CC="/Applications/microchip/xc32/v4.60/bin/xc32-gcc"
MP_CPPC="/Applications/microchip/xc32/v4.60/bin/xc32-g++"
MP_AS="/Applications/microchip/xc32/v4.60/bin/xc32-as"
MP_LD="/Applications/microchip/xc32/v4.60/bin/xc32-ld"
MP_AR="/Applications/microchip/xc32/v4.60/bin/xc32-ar"
MP_CC_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_CPPC_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_AS_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_LD_DIR="/Applications/microchip/xc32/v4.60/bin"
MP_AR_DIR="/Applications/microchip/xc32/v4.60/bin"

ifeq ($(TYPE_IMAGE), DEBUG_RUN)
IMAGE_TYPE=debug
OUTPUT_SUFFIX=elf
DEBUGGABLE_SUFFIX=elf
OUTPUT_FILE=${DISTDIR}/$(PROJECT).${IMAGE_TYPE}.${OUTPUT_SUFFIX}
else
IMAGE_TYPE=production
OUTPUT_SUFFIX=hex
DEBUGGABLE_SUFFIX=elf
OUTPUT_FILE=${DISTDIR}/$(PROJECT).${IMAGE_TYPE}.${OUTPUT_SUFFIX}
endif

OBJECTDIR=build/${CONF}/${IMAGE_TYPE}
DISTDIR=dist/${CONF}/${IMAGE_TYPE}
SRC_DIRS := src
SOURCEFILES := $(shell find $(SRC_DIRS) -type f \( -name '*.c' -o -name '*.S' \))
OBJECTFILES := $(patsubst src/%, $(OBJECTDIR)/src/%, $(SOURCEFILES:.c=.o))
OBJECTFILES := $(OBJECTFILES:.S=.o)

CFLAGS=
ASFLAGS=
LDLIBSOPTIONS=

CFLAGS += -ffunction-sections -fdata-sections -O1 -fno-common \
	-mprocessor=$(CPU) \
	-DHAVE_CONFIG_H -DWOLFSSL_IGNORE_FILE_WARN \
	-I"src" -I"src/config/pic32mz_ef_sk" -I"src/config/pic32mz_ef_sk/library" \
	-I"src/config/pic32mz_ef_sk/library/tcpip/src" \
	-I"src/config/pic32mz_ef_sk/library/tcpip/src/common" \
	-I"src/third_party/wolfssl" -I"src/third_party/wolfssl/wolfssl" \
	-Werror -Wall
ASFLAGS += -Wa,--defsym=__MPLAB_BUILD=1 \
	-Wa,--gdwarf-2 \
	-mprocessor=$(CPU) 

$(OBJECTDIR)/%.o : CFLAGS += -MP -MMD -MF "$@.d"
$(OBJECTDIR)/%.o : ASFLAGS += -MP -MMD -MF "$@.d"

ifeq ($(TYPE_IMAGE),DEBUG_RUN)
CFLAGS += -D__DEBUG \
	-D__MPLAB_DEBUGGER_ICD4=1 \
	-fframe-base-loclist
ASFLAGS += -D__DEBUG \
	-D__MPLAB_DEBUGGER_ICD4=1 \
    -Wa,--defsym=__MPLAB_DEBUG=1 \
    -Wa,--defsym=__MPLAB_DEBUGGER_ICD4=1 \
    -Wa,--gdwarf-2
endif

$(OBJECTDIR)/%.o : %.S
	@mkdir -p $(dir $@)
	@echo Assembling $<
	$(MP_CC) $(MP_EXTRA_AS_PRE) -x assembler-with-cpp -c \
		$(ASFLAGS) \
		-o $@ \
		$< \
		-DXPRJ_pic32mz_ef_sk=$(CONF) -mdfp="$(DFP_DIR)"

$(OBJECTDIR)/%.o : %.c
	@mkdir -p $(dir $@)
	@echo Compiling $<
	$(MP_CC) $(MP_EXTRA_CC_PRE) -x c -c $(CFLAGS) \
		-o $@ \
		$<

LDFLAGS_COMMON = \
	-mprocessor=$(CPU) \
	-Wl,--defsym=__MPLAB_BUILD=1$(MP_EXTRA_LD_POST) \
	-Wl,--script=$(CPULD) \
	-Wl,--defsym=_min_heap_size=64960 \
	-Wl,--gc-sections \
	-Wl,--no-code-in-dinit \
	-Wl,--no-dinit-in-serial-mem \
	-Wl,-Map="$(DISTDIR)/$(PROJECT).$(IMAGE_TYPE).map" \
	-Wl,--memorysummary,$(DISTDIR)/memoryfile.xml \
	-mdfp="$(DFP_DIR)"
	
ifeq ($(TYPE_IMAGE),DEBUG_RUN)
LDFLAGS_EXTRA = \
	-g -mdebugger -D__MPLAB_DEBUGGER_ICD4=1 \
	-Wl,--defsym=__MPLAB_DEBUG=1 \
	-Wl,--defsym=__DEBUG=1 \
	-Wl,--defsym=__MPLAB_DEBUGGER_ICD4=1
OUTPUT_FILE := $(DISTDIR)/$(PROJECT).$(IMAGE_TYPE).$(OUTPUT_SUFFIX)
POST_LINK :=
else
LDFLAGS_EXTRA =
OUTPUT_FILE := $(DISTDIR)/$(PROJECT).$(IMAGE_TYPE).$(DEBUGGABLE_SUFFIX)
POST_LINK := $(MP_CC_DIR)/xc32-bin2hex $(OUTPUT_FILE)
endif
	
$(OUTPUT_FILE): $(OBJECTFILES) Makefile src/config/pic32mz_ef_sk/p32MZ2048EFH100.ld
	@mkdir -p $(DISTDIR)
	@echo Linking $@
	$(MP_CC) $(MP_EXTRA_LD_PRE) $(LDFLAGS_EXTRA) $(LDFLAGS_COMMON) \
		-o $@ $(OBJECTFILES) \
		-DXPRJ_pic32mz_ef_sk=$(CONF)
	$(POST_LINK)

#
# When we build, we create the compiled hex or elf file that we can 
# load into the processor.
#
build: $(OUTPUT_FILE)

#
# When we clean, we remove all files and directories in the object and
# distribution directory trees.
#
clean:
	rm -fr ${OBJECTDIR}
	rm -fr ${DISTDIR}

#
# We have told the compiler to create a dependency makefiles for every object it
# creates, which lists the source and header files included in the compile.
# These dependency files contain a recipe for building the object that lists its
# dependencies. By this means, Make will look at all the header files required
# by an object and re-compile the object if any of the headers is modified.
#
DEPFILES := $(OBJECTFILES:.o=.o.d)
-include $(DEPFILES)