/*
	main.c -- Embedded Ethernet Module (EEM) Main Program.

	The EEM is a programmable TCP/IP server built on a Mini Peripheral
	Connection Interface Express (mPCIe) card. The EEM plugs into an mPCIe
	socket on its host board. The EEM uses a PIC32MZ2048EFH microcontroller and
	LAN8720A Ethernet physical layer to provide computing, memory, and
	networking. The host provides the EEM with 3.3-V power and an RJ-45 socket
	with internal magnetics for the EEM's 100-Base-T network interface. The host
	provides a pin header of some sorth through which we can program the EEM's
	microcontroller with the code compiled from this repository. The host can
	also provide three pins for the EEM's UART console interface. The mPCIe pins
	on the EEM provide all eighteen connections needed for an eight-bit parallel
	bus: eight data lines, eight address lines, one data strobe, and one write
	line. This data bus is the means by which the EEM communicates with the
	host. In all our EEM applications, the EEM is the master of this bus, and it
	uses the bus to configure and control the host. We use the EEM to provide
	TCP/IP access to a host board.

	This is the main program of our P3053 repository, where "3053" is the Open
	Source Instruments Inc. assembly number for the Embedded Etherenet Module.
	The repository contains hundreds files from from Microchip's Harmony
	library. The Harmony files provide the driver for our Ethernet physical
	layer (LAN8720A), the TCP/IP stack, utilities like "ping", and provide
	access to the PIC32MZ's interrupts, configuration registers, flash memory,
	system timers, peripheral interfaces, and peripheral pin selection (PPS).

	In server.c, we providesa generic server state machine, which we use to
	provide LWDAQ and Telnet servers. We trust that the server state machiune
	can be deployed for any server protocol with little or no modification. In
	pic.c we provide routines to access the mPCIe bus. In console.c we have
	routines to print to the UART2 console, which is always enabled, even if
	unconnected. A global "debug" flag allows us to enable console print
	instructions only for the debug build. In lwdaq.c we provide implementation
	of our own LWDAQ server protocol. In main.c we provide our Telnet server,
	which we enable only in the debug build. In cli.c we provide a generic
	Command-Line Interpreter (CLI) that we can attach to multiple communication
	channels at once. We attach the CLI to the PIC32MZ's UART2 interface, and in
	the debug build, we attach the CLI to our Telnet server as well. In main.c
	we register a set of commands with the CLI. These commands provide access to
	the TCP/IP configuration, the overal EEM configuration, the mPCIe bus, and
	allow us to reset the EEM. Management of the configuration of the EEM, which
	we want to store in flash memory so that it persists through power cycles,
	is provided by server.c. We use a system of storing configuration records to
	flash memory and reading them from flash memory when the EEM boots up. We
	can configure the EEM through the long-standing LWDAQ Configurator Tool, or
	we can do so with the CLI over Telnet or through the Console.

	The P3053 repository began as a Microchip demonstration package generated by
	their MPLAB Harmony Configurator. We replaced the three makefiles of this
	repository with one makefile that detects all source files, compiles them,
	and links them. We simplified the file structure. We removed the WolfSSL
	libraries from the demonstration package and disabled the Harmony Crypto
	libraries. We provided our own random integer routine to replace the one
	Crypto library routine that our TCP/IP stack was using. Our makefile
	recognises two type of build: "release" and "debug". These are compiled into
	two different directories. The only difference between them is the state of
	the global "debug" flag, which is cleared for release and set for debug. We
	use the debug flag to enable debug printouts embedded in the code.

	The Harmony files in this repository retain their original Microchip
	copyright statements without modification. The top-level files are provided
	by Open Source Instruments Inc. (OSI). These we distribute under the GNU
	General Public License (GPL). The GPL is far more restrictive than the
	Microchip license. Anyone incorporating GPL files into their own work must
	release the completed work under GPL as well.

	Copyright (C) 2025, Kevan Hashemi, Open Source Instruments Inc.

	This program is free software: you can redistribute it and/or modify it
	under the terms of the GNU General Public License as published by the Free
	Software Foundation, either version 3 of the License, or (at your option)
	any later version.

	This program is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
	FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
	more details.

	You should have received a copy of the GNU General Public License along with
	this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>				  
#include <stdbool.h>
#include <stdlib.h>
#include <stdarg.h>
#include "configuration.h"
#include "definitions.h"
#include "utils.h"
#include "pic.h"
#include "cli.h"
#include "console.h"
#include "server.h"
#include "lwdaq.h"

/*
	Declare the constants and structures that configure our Telnet server. The
	Telnet server, which should be made available in all debug builds. We must
	assign the port pointer before trying to start the Telnet server.
*/
#define DEFAULT_TELNET_PORT 23
tcpip_server_type telnet_server = {
    .protocol = "Telnet",
    .socket = INVALID_SOCKET,
    .state = S_WAIT_STACK,
    .port_ptr = NULL,
    .bound_port = 0,
    .ip_str = NULL,
    .bound_ip_str = "0.0.0.0",
    .logged_in = false
};
#ifdef VERBOSE_CONSOLE
static const bool telnet_enable = true;
#else
static const bool telnet_enable = false;
#endif

/*
	telnet_getchar removes Telnet commands from the input stream so as to make
	the stream compatible with our Command-Line Interpreter (CLI). Most of the
	characters in these commands are non-printable characters, but some are not,
	and they can reappear in the input stream at any time. This routine is not
	re-entrant. It may be used by only one Telnet client at a time. Furthermore,
	the routine assumes that Telnet control verbs 0xFB, 0xFC, 0xFD, and 0xFE
	will never be present in the input stream unless followed by an option
	character that we must ignore. We do not expect our CLI user to be entering
	these values, and if they do, the behavior of our CLI is indeterminate. Like
	all CLI-compatible getchar routines, this getchar returns -2 if the socket
	is closed, -1 if no characters are available, and the character if it finds
	one.	
*/
int telnet_getchar(void *context) {
    static bool waiting_for_option = false;
    int c;
    
    while (true) {
		c = tcp_getchar(context);
		if (c < 0) return c;
		if (waiting_for_option) {
			waiting_for_option = false;
			continue;
		}
		if (c == 0xFF) continue;
		if (c == 0xFB || c == 0xFC || c == 0xFD || c == 0xFE) {
			waiting_for_option = true;
			continue;
		}
		if (cli_accept_char((char) c)) {
			return c;
		}
		continue;
    }
	return -1;
}

/*
	telnet_tasks services a Telnet connection with a Command-Line Interpreter
	(CLI). Consult the CLI header and implementation files for details of how
	the CLI works. In the case of Telnet, it does not echo characters, but
	assumes the client is buffering characters on each line. The CLI uses a
	channel descriptor record to manage communication with the TCP socket. We
	configure this descriptor when the socket starts listening for a connection.
*/
int telnet_tasks(tcpip_server_type* server) {
	static cli_chan_type telnet_chan;
		 
	if (server->state == S_LISTENING) {
		server->logged_in = false;
   		telnet_chan.getchar = telnet_getchar;
		telnet_chan.putchar = tcp_putchar;
		telnet_chan.flush = tcp_flush;
		telnet_chan.context  = (void *) &server->socket;
		telnet_chan.echo = false;
		telnet_chan.name = "CLI-Telnet";
		cli_start(&telnet_chan);
		if (debug) console_print("Initialized %s connection in %s.\n",
			server->protocol, __func__);
		return 0;
	};

	cli_server(&telnet_chan);
	return 0;
}

/*
	lamp_signal uses an unsigned integer code, and an internal index, to apply
	signals to the green lamp (d2) and the red lamp (d5). The blue (d3) and
	white (d4) lamps are used by the UART2 console, so will show if the console
	is enabled, and if a USB-to-UART bridge is connected. We will use d3 as a
	power indicator, turning it on for 10% of the time so quickly that it looks
	constant and dim so long as the loop is executing quickly. We will use d5 as
	a heartbeat, flashing it every one or two seconds in the main loop, and five
	or ten times a second in the networks startup loop. Both these flashs will
	be slowed down if the loop tasks start to take hundreds of milliseconds to
	complete, and stop entirely if we get stuck somewhere or the EEM crashes.
*/
void lamp_signal(uint32_t period) {
	static uint32_t i = 0;
	
	if (period == 0) {
		pic_d2_on();
   		pic_d5_on();
   		i = 0;
   		return;
	} else {
		i++;
		if (i % 100 == 0) pic_d2_off();
		if (i % 1000 == 0) pic_d2_on();
		if (i % 10000 == 0) pic_d5_off();
		if (i == period) {
			pic_d5_on();
			i = 0;
		}
		return;
	}
}

/*
	The main program, from which all other programs are called. We initialize
	all Embedded Ethernet Module (EEM) system processes. We wait for the TCP/IP
	stack to start up. We assert IP configuration we read from flash memory. We
	enter the task management loop, in which we attend to our console and our
	server sockets. During the network startup delay, and during the task
	management loop, we manipulate the indicator lamps to show that the EEM is
	running, which loop it is in, and whether the loop is slowing down with the
	burden of its tasks.
*/
int main (void) {

	/*
		Initialize the microcontroller and its peripherals, which include clock,
		memory, core timers, system timer, UART console, Ethernet physical
		interface, and the TCP/IP stack. Configure the general-purpose
		input-output pins to communicate with indicator lamps, test pins, and
		the eight-bit parallel bus.
	*/
	pic_initialize();
	
	/*
		Register commands in the Command-Line Interpreter (CLI). This is the only 
		initialization the CLI requires.
	*/
	cli_cmd_register("help",cli_help);
	cli_cmd_register("reset",cli_reset);
	cli_cmd_register("eem-config",cli_eem_config);
	cli_cmd_register("ip-config",cli_ip_config);
	cli_cmd_register("pic-info",cli_pic_info);
	cli_cmd_register("mpcie",cli_mpcie);
	
	/*
		Start up the lamp signaling.
	*/
	lamp_signal(0);
	
	/*
		Check the configuration switch on the host board. If it is depressed,
		the least significant bit of location forty will be zero. If depressed,
		write the factory EEM configuration to flash, for factory reset. Read
		the flash configuration int the active configuration.
	*/
	uint8_t val = mpcie_byte_read(40);
   	if ((val & 0x01) == 0) {
   		console_message("FACTORY RESET: Configuration switch pressed on host board.\n");
    	eem_config_write(&eem_config_factory);
	}
	eem_config_read(&eem_config_active);

   	/*
		Wait for the TCP/IP stack to establish itself. Once the stack is ready,
		we apply our IP address, gateway address, and network mask, as read from
		the active configuration. Lamp signaling shows that the EEM is alive
		during the wait.
   	*/
   	while (TCPIP_STACK_Status(sysObj.tcpip) != SYS_STATUS_READY) { 
   		tcpip_tick();
   		lamp_signal(1e5);
   	}
   	server_set_ip(eem_config_active.ip_str, 
   		eem_config_active.gw_str,
   		eem_config_active.nm_str);
 
 	/*
 		Start up a Command-Line Interpreter (CLI) for the console interface,
 		which runs on UART2 in this version of the EEM.
 	*/
 	static cli_chan_type console_chan;
	console_chan.getchar = uart2_getchar;
	console_chan.putchar = uart2_putchar;
	console_chan.flush = uart2_flush;
	console_chan.context  = NULL;
	console_chan.echo = true;
	console_chan.name = "CLI-Console";
	cli_start(&console_chan);
	
	/* 
		Set the source of the LWDAQ and Telnet server IP addresses and TCP ports.
	*/
	lwdaq_server.ip_str = &eem_config_active.ip_str[0];	
	lwdaq_server.port_ptr = &eem_config_active.lwdaq_port;	
	telnet_server.ip_str = &eem_config_active.ip_str[0];
	telnet_server.port_ptr = &eem_config_active.telnet_port;

   	/*
   		This loop should never terminate. We perform maintenance tasks one
   		after another. The lamp signaling will show that the EEM is alive.
   	*/
	while (true) {
		tcpip_tick();
		cli_server(&console_chan);
		tcpip_server(&lwdaq_server, lwdaq_tasks);
		if (telnet_enable) tcpip_server(&telnet_server, telnet_tasks);
		lamp_signal(5e5);
	}
	
	return (EXIT_FAILURE);
}


