/*
	main.c -- Embedded Ethernet Module (EEM) Main Program.

	This program calls initialization routines and implements the main event
	loop. It is the top-level program of our P3053 repository, which, when
	compiled into a HEX programming file, we can load into the PIC32MZ2048EFH of
	our Embedded Ethernet Module (A3053). The A3053 is a programmable TCP/IP
	server with an eight-bit parallel bus mounted on an MPCIE card. We plan
	several versions of the A3053. The first version is the A3053A, on a printed
	circuit board that failed to provide a convenient connection to the UART2,
	and failed to connect the MPCIE parallel bus to PIC pins that would permit
	efficient implementation of bus access. The next version, the A3053B will
	improve the pin allocations. Additional numbers may follow the assembly
	number to specify minor modifications to the circuit. The version of the
	software running on the PIC, which we will call the circuit "firmware", we
	will specify with a letter after a dash. So the A3053B3-C6 is the A3053B
	assembly, minor version 3, with firmware version C, minor version 6. We will
	be maintaining separate repositories for the separate main assembly numbers,
	so we will have P3053A for the A3053A and P3053B for the A3053B. We'll see
	how that works out. We may find that it's easier to combine them into one
	and pick which we want with some compiler flags.

	The P3053 repository is equipped with hundreds files taken from Microchip's
	Harmony3 library suite. These libraries provide a driver for our Ethernet
	physical layer (LAN8720A). They provide implementations of the UDP, TCP, and
	IP protocols. They provide utilities like "ping". We have libraries that
	give access to all features of the A3053's PIC32MZ2048EFH microcontroller:
	interrupts, configuration registers, non-volatile memory, system timers,
	peripheral interfaces, and peripheral pin selection (PPS).
	
	The P3053 repository began as a Microchip demonstration package generated by
	their MPLAB Harmony Configurator. We replaced the three makefiles of this
	repository with one makefile that detects all source files automatically,
	compiles them, and links them. We simplified the file structure. We removed
	the WolfSSL libraries and disabled the Harmony Crypto libraries, providing
	our own random integer routine to replace the one Crypto library routine
	that our TCP/IP stack was using. Our makefile recognises two type of build
	"release" and "debug". These are compiled into two different build
	directories. The only difference between them is the state of the global
	"debug" flag, which is cleared for release and set for debug.

	The files in this repository have two authors. The vast majority of them are
	provided by Microchip. These remain, for the most part, untouched with their
	Microchip copyright statements intact. The top-level files are provided by
	Open Source Instruments Inc. (OSI), and these are covered by the GNU General
	Public License, which is more strict than the Microsoft license, see license
	statement below our copyright. Anyone incorporating the OSI into their own
	work must release the entire work under the same license.

	Copyright (C) 2025, Kevan Hashemi, Open Source Instruments Inc.

	This program is free software: you can redistribute it and/or modify it
	under the terms of the GNU General Public License as published by the Free
	Software Foundation, either version 3 of the License, or (at your option)
	any later version.

	This program is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
	FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
	more details.

	You should have received a copy of the GNU General Public License along with
	this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>				  
#include <stdbool.h>
#include <stdlib.h>
#include <stdarg.h>
#include "configuration.h"
#include "definitions.h"
#include "utils.h"
#include "pic.h"
#include "cli.h"
#include "console.h"
#include "server.h"
#include "lwdaq.h"

/*
	Declare the constants and structures that configure our Telnet server. The
	Telnet server we assume will be available to any implementation of the
	A3053, provided that the VERBOSE_CONSOLE macro is defined, which is our way
	of enabling debugging features.
*/
#define TELNET_PORT 23
tcpip_server_type telnet_server = {
	INVALID_SOCKET,
	S_WAIT_STACK,
	TELNET_PORT,
	"Telnet"
};
#ifdef VERBOSE_CONSOLE
static const bool telnet_enable = true;
#else
static const bool telnet_enable = false;
#endif

/*
	telnet_getchar removes Telnet commands from the input stream so as to make
	the stream compatible with our Command-Line Interpreter (CLI). Most of the
	characters in these commands are non-printable characters, but some are not,
	and they can reappear in the input stream at any time. This routine is not
	re-entrant. It may be used by only one Telnet client at a time. Furthermore,
	the routine assumes that Telnet control verbs 0xFB, 0xFC, 0xFD, and 0xFE
	will never be present in the input stream unless followed by an option
	character that we must ignore. We do not expect our CLI user to be entering
	these values, and if they do, the behavior of our CLI is indeterminate. Like
	all CLI-compatible getchar routines, this getchar returns -2 if the socket
	is closed, -1 if no characters are available, and the character if it finds
	one.	
*/
int telnet_getchar(void *context) {
    static bool waiting_for_option = false;
    int c;
    
    while (true) {
		c = tcp_getchar(context);
		if (c < 0) return c;
		if (waiting_for_option) {
			waiting_for_option = false;
			continue;
		}
		if (c == 0xFF) continue;
		if (c == 0xFB || c == 0xFC || c == 0xFD || c == 0xFE) {
			waiting_for_option = true;
			continue;
		}
		if (cli_accept_char((char) c)) {
			return c;
		}
		continue;
    }
	return -1;
}

/*
	telnet_tasks services a Telnet connection.
*/
int telnet_tasks(tcpip_server_type* server) {
	static cli_chan_type cli_chan;
		 
	if (server->state == S_LISTENING) {
   		cli_chan.getchar = telnet_getchar;
		cli_chan.putchar = tcp_putchar;
		cli_chan.flush = tcp_flush;
		cli_chan.context  = (void *) &server->socket;
		cli_chan.name = "CLI-Telnet";
		cli_start(&cli_chan);
		if (debug) console_print("Initialized %s connection in %s.\r\n",
			server->protocol, __func__);
		return 0;
	};

	cli_server(&cli_chan);
	return 0;
}

/*
	The main program, from which all other programs are called. In our case, we 
	initialize the PIC processes, then enter an infinite loop from which there
	should be no escape. So far as we can tell, the main program should return
	an integer, so we return EXIT_FAILURE if ever the program escapes our loop.
*/
int main (void) {

	/*
		Initialize the microcontroller and its peripherals, which include clock,
		memory, core timers, system timer, UART console, Ethernet physical
		interface, and the TCP/IP stack. Configure the general-purpose
		input-output pins to communicate with indicator lamps, test pins, and
		the eight-bit parallel bus.
	*/
	pic_initialize();
	
	/*
		Initialize the command-line interpreter. This involves nothing more than
		registering commands.
	*/
	cli_initialize();
	
	/*
		Set up the embedded ethernet module for this particular appliction. Here
		we turn on both the green LED (D2) and the red LED (D5) on an A3053A.
		The white and blue LED pins are used for our UART2 console. We will use
		D2 as a power indicator, turning it on for 10% of the time so quickly
		that it looks constant and dim so long as the loop is executing quickly.
		We will use D5 as a heartbeat, flashing it every one or two seconds.
		This flash will be disrupted if the loop tasks start to take hundreds of
		milliseconds to complete.
	*/
   	pic_d2_on();
   	pic_d5_on();
 
   	/*
   		This loop should never terminate. We perform maintenance tasks one after
   		another. A loop counter allows us to blink lights to show heartbeat and 
   		power.
   	*/
	int i = 0;
	while (true) {
		tcp_tick();
		console_server();
		tcpip_server(&lwdaq_server, lwdaq_tasks);
		if (telnet_enable) {
			tcpip_server(&telnet_server, telnet_tasks);
		}

		i = i+1;
		if (i % 100 == 0) pic_d2_off();
		if (i % 1000 == 0) pic_d2_on();
		if (i % 10000 == 0) pic_d5_off();
		if (i == 500000) {
			pic_d5_on();
			i = 0;
		}
	}
	
	return (EXIT_FAILURE);
}


