/*
	main.c -- Embedded Ethernet Module (EEM) Main Program.

	The EEM is a programmable TCP/IP server built on a Mini Peripheral
	Connection Interface Express (mPCIe) card. The EEM plugs into an mPCIe
	socket on its motherboard. The EEM uses a PIC32MZ2048EFH microcontroller
	and LAN8720A Ethernet physical layer to provide computing, memory, and
	networking. The motherboard provides the EEM with 3.3-V power and an RJ-45
	socket with internal magnetics for the EEM's 100-Base-T network interface.
	The motherboard provides a pin header of some sorth through which we can
	program the EEM's microcontroller with the code compiled from this
	repository. The motherboard can also provide three pins for the EEM's UART
	console interface. The mPCIe pins on the EEM provide all eighteen
	connections needed for an eight-bit parallel bus: eight data lines, eight
	address lines, one data strobe, and one write line. This data bus is the
	means by which the EEM communicates with the motherboard. In all our EEM
	applications, the EEM is the master of this bus, and it uses the bus to
	configure and control the motherboard. We use the EEM to provide TCP/IP
	access to a motherboard.

	This is the main program of our P3053 repository, where "3053" is the Open
	Source Instruments Inc. (OSI) assembly number for the Embedded Etherenet
	Module. The repository contains hundreds files from from Microchip's
	"Harmony3 Library", which we will refer to in our comments a as the
	"Microchip Library". Our Microchip Library files are stored in
	/src/microchip directory. They provide the driver for our Ethernet physical
	layer (LAN8720A), the TCP/IP stack, utilities like "ping", and provide
	access to the PIC32MZ's interrupts, configuration registers, flash memory,
	system timers, peripheral interfaces, and peripheral pin selection (PPS).

	The source code provided by OSI is in the /src directory. With server.c, we
	providesa generic server state machine, which we use to provide LWDAQ and
	Telnet servers. We trust that the server state machiune can be deployed for
	any server protocol with little or no modification. In pic.c we provide
	routines to access the mPCIe bus. In console.c we have routines to print to
	the UART2 console, which is always enabled, even if unconnected. A global
	"debug" flag allows us to enable console print instructions only for the
	debug build. In lwdaq.c we provide implementation of our own LWDAQ server
	protocol. In main.c we provide a Telnet server, which we enable with a
	compiler directive. In cli.c we provide a generic Command-Line Interpreter
	(CLI) that we can attach to multiple communication channels at once. We
	attach the CLI to the PIC32MZ's UART2 interface, and in the debug build, we
	attach the CLI to our Telnet server as well. In main.c we register a set of
	commands with the CLI. These commands provide access to the TCP/IP
	configuration, the overal EEM configuration, the mPCIe bus, and allow us to
	reset the EEM. Management of the configuration of the EEM, which we want to
	store in flash memory so that it persists through power cycles, is provided
	by server.c. We use a system of storing configuration records to flash
	memory and reading them from flash memory when the EEM boots up. We can
	configure the EEM through the long-standing LWDAQ Configurator Tool, or we
	can do so with the CLI over Telnet or through the Console.

	The P3053 repository began as a Microchip demonstration package generated by
	their MPLAB Harmony Configurator. We replaced the three makefiles of this
	repository with one makefile that detects all source files, compiles them,
	and links them. We simplified the file structure. We removed the WolfSSL
	libraries from the demonstration package and disabled the Harmony Crypto
	libraries. We provided our own random integer routine to replace the one
	Crypto library routine that our TCP/IP stack was using. Our makefile
	recognises two type of build: "release" and "debug". These are compiled into
	two different directories. The only difference between them is the state of
	the global "debug" flag, which is cleared for release and set for debug. We
	use the debug flag to enable debug printouts embedded in the code.

	The Microchip Harmony3 files in this repository retain their original
	Microchip copyright statements without modification. The top-level files are
	provided by Open Source Instruments Inc. (OSI). These we distribute under
	the GNU General Public License (GPL). The GPL is far more restrictive than
	the Microchip license. Anyone incorporating GPL files into their own work
	must release the completed work under GPL as well.

	Copyright Copyright (C) 2025-2026, Kevan Hashemi, Open Source Instruments Inc.

	This program is free software: you can redistribute it and/or modify it
	under the terms of the GNU General Public License as published by the Free
	Software Foundation, either version 3 of the License, or (at your option)
	any later version.

	This program is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
	FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
	more details.

	You should have received a copy of the GNU General Public License along with
	this program. If not, see <https://www.gnu.org/licenses/>.
*/

/*
	The standard C headers we trust the compiler will know how to find. The
	Microchip library headers are configuration.h and definitions.h. The
	compiler must be told where to look for these two files. The remaining
	interfaces are those that go with our EEM implementation files.
*/
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>				  
#include <stdbool.h>
#include <stdlib.h>
#include <stdarg.h>
#include "configuration.h"
#include "definitions.h"
#include "utils.h"
#include "config.h"
#include "pic.h"
#include "cli.h"
#include "console.h"
#include "server.h"
#include "lwdaq.h"

/*
	Declare the structures and fields that configure our Telnet server. If we
	want a timeout, we must set the timeout in seconds as well. We disable the
	Telnet server by setting the telnet_port field of the flash EEM
	configuration to zero.
*/
tcpip_server_type telnet_server = {
	.network_up = false,
	.ip_assigned = false,
	.sock_init = true,
	.logged_in = false,
    .protocol = "Telnet",
    .ip_str = "0.0.0.0",
    .port = DEFAULT_TELNET_PORT,
    .tcp_timeout = 0,
    .last_tick = 0,
    .socket = INVALID_SOCKET,
    .listening = INVALID_SOCKET,
    .indicator = d3_on
};

/*
	telnet_getchar removes Telnet commands from the input stream so as to make
	the stream compatible with our Command-Line Interpreter (CLI). Most of the
	characters in these commands are non-printable characters, but some are not,
	and they can reappear in the input stream at any time. This routine is not
	re-entrant. It may be used by only one Telnet client at a time. Furthermore,
	the routine assumes that Telnet control verbs 0xFB, 0xFC, 0xFD, and 0xFE
	will never be present in the input stream unless followed by an option
	character that we must ignore. We do not expect our CLI user to be entering
	these values, and if they do, the behavior of our CLI is indeterminate. Like
	all CLI-compatible getchar routines, this getchar returns -2 if the socket
	is closed, -1 if no characters are available, and the character if it finds
	one.	
*/
int telnet_getchar(void *context) {
    static bool waiting_for_option = false;
    int c;
    
    while (true) {
		c = tcp_getchar(context);
		if (c < 0) return c;
		if (waiting_for_option) {
			waiting_for_option = false;
			continue;
		}
		if (c == 0xFF) continue;
		if (c == 0xFB || c == 0xFC || c == 0xFD || c == 0xFE) {
			waiting_for_option = true;
			continue;
		}
		if (cli_accept_char((char) c)) {
			return c;
		}
		continue;
    }
	return -1;
}

/*
	telnet_tasks services a Telnet connection with a Command-Line Interpreter
	(CLI). Consult the CLI header and implementation files for details of how
	the CLI works. In the case of Telnet, it does not echo characters, but
	assumes the client is buffering characters on each line. The CLI uses a
	channel descriptor record to manage communication with the TCP socket. We
	configure this descriptor when the socket starts listening for a connection.
*/
int telnet_tasks(tcpip_server_type *server) {
	static cli_chan_type telnet_chan;
		 
	if (server->sock_init) {
		server->logged_in = false;
		telnet_chan.status = CLI_CONNECTED;
   		telnet_chan.getchar = telnet_getchar;
		telnet_chan.putchar = tcp_putchar;
		telnet_chan.flush = tcp_flush;
		telnet_chan.context  = (void *) &server->socket;
		telnet_chan.echo = false;
		telnet_chan.name = "CLI-Telnet";
		strcpy(telnet_chan.prompt, "");
		cli_start(&telnet_chan);
		if (debug) console_print("Initialized %s connection in %s.\n",
			server->protocol, __func__);
		return 0;
	};

	cli_server(&telnet_chan);
	switch (telnet_chan.status) {
		case CLI_CONNECTED: 
			server->logged_in = false;
			return 0;
		
		case CLI_PASS:
			server->logged_in = true;
			return 0;
			
		case CLI_FAIL:
			server->logged_in = false;
			return 0;
		
		case CLI_CLOSE:
			server->logged_in = false;
			return EEM_SOCK_END;

		default:
			server->logged_in = false;
			return EEM_SOCK_ERR;
	} 
}

/*
	lamp_signal uses an unsigned integer period and an internal index to apply
	signals to the green lamp (d2) and the red lamp (d5). We use these lamps to
	indicate the state and activity of the EEM. 
	
	+----------------------------------------+--------------+----------------------+
	| EEM State                              | Green        | Red                  |
	+----------------------------------------+--------------+----------------------+
	| Booting up                             | OFF          | OFF                  |
	| MCU Initialized                        | ON           | ON                   |
	| Waiting for network interface to start | 10%          | ON, blink off        |
	| Network interface up, linked, idle     | 10%          | OFF, heartbeat flash |
	| Network interface up, linked, busy     | 10%, flicker | OFF, irregular flash |
	| Network interface up, no link          | 10%          | ON, blink off        |
	| Network interface down                 | 10%          | ON                   |
	| Crashed, frozen, or stuck in loop      | OFF or ON    | OFF or ON            |
	+----------------------------------------+--------------+----------------------+	
	
	The heartbeat flash should be a quick flash ever one or two seconds. The
	blink off should be a half-second of the lamp off every one or two seconds.
	When the EEM is laboring with server tasks, the main loop calls lamp_signal
	less often. The green lamp starts to flicker. When the EEM is stretched to
	the limit, the green light will be blinking at full power several times a
	second and the red light will be blinking at full power once every few
	seconds.

	If the EEM loses its link, the red light will blink off once a second. If
	the EEM freezes, the red and green lamps will each either be fully on or
	fully off, depending upon their state immediately before the freeze. If the
	EEM is unresponsive and we see both lights shining, look at the green light
	more carefully, moving your eye around. If the green light is turning on and
	off, you will see its image flickering as you move your eye. This flicker
	means the EEM main loop is running. The red light being on means the network
	interface is down. But if the green light does not flicker, it must be at
	full power. The red light is stuck on. The EEM has crashed or is stuck in a
	loop.
*/
void lamp_signal(uint32_t period) {
	static uint32_t i = 0;
	
	if (period == 0) {
		d2_on(true);
   		d5_on(true);
   		i = 0;
   		return;
	} else {
		i++;
		if (i % 100 == 0) d2_on(false);
		if (i % 1000 == 0) d2_on(true);
		if (server_network_up() && server_link_up() && i == 10000) {
			d5_on(false);
		}
		if (server_network_up() && !server_link_up() && i == period - 100000) {
			d5_on(false);
		}
		if (i == period) {
			d5_on(true);
			i = 0;
		}
		return;
	}
}

/*
	The main program. We initialize all Embedded Ethernet Module (EEM) system
	processes. We wait for the TCP/IP stack to start up. We assert IP
	configuration we read from flash memory. We enter the task management loop,
	in which we attend to our console and our server sockets. During the network
	startup delay, and during the task management loop, we manipulate the
	indicator lamps to show that the EEM is running, which loop it is in, and
	whether the loop is slowing down with the burden of its tasks.
*/
int main (void) {

	// Initialize the microcontroller and its peripherals, which include clock,
	// memory, core timers, system timer, UART console, Ethernet physical
	// interface, and the TCP/IP stack. Configure the general-purpose
	// input-output pins to communicate with indicator lamps, test pins, and
	// the eight-bit parallel bus.
	pic_initialize();

	// Register commands in the Command-Line Interpreter (CLI). This is the only 
	// initialization the CLI requires. The "help" command will list the commands
	// in the order we register them.
	cli_cmd_register("config",cli_config);
	cli_cmd_register("debug",cli_debug);
	cli_cmd_register("exit",cli_exit);
	cli_cmd_register("gpio",cli_gpio);
	cli_cmd_register("help",cli_help);
	cli_cmd_register("lamp",cli_lamp);
	cli_cmd_register(CLI_LOGIN_CMD,cli_login);
	cli_cmd_register("mpcie",cli_mpcie);
	cli_cmd_register("prompt",cli_prompt);
	cli_cmd_register("status",cli_status);
	cli_cmd_register("reset",cli_reset);
	
	// Wait for the power supplies to settle before we check the configuration
	// switch. If we read the switch location too soon, we will think it is
	// depressed when it is not.
	lamp_signal(0);
	uint32_t last_tick = SYS_TMR_TickCountGet();
	while (SYS_TMR_TickCountGet() - last_tick < EEM_POWERUP_WAIT_MS) {
		tcp_tick();
	}
	
	// Check the configuration switch on the motherboard. If it is depressed,
	// the least significant bit of location forty will be zero. If depressed,
	// write the factory EEM configuration to flash, for factory reset.
	uint8_t val = mpcie_byte_read(40);
   	if ((val & 0x01) == 0) {
   		console_message("FACTORY RESET: Detected configuration switch depressed.\n");
    	eem_config_write(&eem_config_factory);
	}
	
	// Read the flash configuration into the active configuration.
	eem_config_read(&eem_config_active);

   	// Wait for the TCP/IP stack to establish itself. Once the stack is ready,
	// we apply our IP address, gateway address, and network mask, as read from
	// the active configuration. Lamp signaling shows that the EEM is alive
	// during the wait.
   	while (TCPIP_STACK_Status(sysObj.tcpip) != SYS_STATUS_READY) { 
   		tcp_tick();
   		lamp_signal(1e5);
   	}
   	server_set_ip(eem_config_active.ip_str, 
   		eem_config_active.gw_str,
   		eem_config_active.nm_str);
 
 	// Start up a Command-Line Interpreter (CLI) for the console interface,
	// which runs on UART2 in this version of the EEM. We start with the
	// console interface status set to 1, so that it is regarded as logged in,
	// and can always read and modify the EEM configuration regardless of the
	// EEM security level, unless it deliberately fails to log itself in using
	// the CLI login command, in which case its state will go to CLI_FAIL.
 	static cli_chan_type console_chan;
	console_chan.getchar = uart2_getchar;
	console_chan.putchar = uart2_putchar;
	console_chan.flush = uart2_flush;
	console_chan.context  = NULL;
	console_chan.echo = true;
	console_chan.name = "CLI-Console";
	strcpy(console_chan.prompt, CLI_PROMPT_DEFAULT);
	console_chan.status = CLI_PASS;
	cli_start(&console_chan);
	
	// Set the LWDAQ and Telnet server ports and timeouts.
	lwdaq_server.port = eem_config_active.lwdaq_port;
	lwdaq_server.tcp_timeout = eem_config_active.lwdaq_timeout;
	telnet_server.port = eem_config_active.telnet_port;
	telnet_server.tcp_timeout = eem_config_active.telnet_timeout;

   	// Perform maintenance tasks one after another and repeat. The lamp
   	// signaling will show that the EEM is alive. 
	while (true) {
		tcp_tick();
		cli_server(&console_chan);
		if (EEM_LWDAQ_ENABLE) tcpip_server(&lwdaq_server, lwdaq_tasks);
		if (EEM_TELNET_ENABLE) tcpip_server(&telnet_server, telnet_tasks);
		lamp_signal(5e5);
	}
	
	// If we ever get here, we should return with a failure code.
	return (EXIT_FAILURE);
}


